### PR TITLE
Add back missing ckeditor/skins files

### PR DESCRIPTION
**Pull request by hzoo**
@mikesherov 

#32

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Is there a related bug issue? Why do these particular ones need to be added back?

**Comment by hzoo** [comment]
Yeah got missing files errors when trying to test my stuff

screen shot 2015-08-14 at 11 40 16 am

**Comment by mrjoelkemp** [comment]
Thanks for clarifying. That's only a single stylesheet though. Why the other 43 files?

**Comment by hzoo** [comment]
It's in case we need them later - mike was only removing non dev files in the other pr?

**Comment by mikesherov** [comment]
:+1:

**Comment by mrjoelkemp** [comment]
:+1:

**Pull request merged**
